main: me.juddcraft12.grapplinghook.GrapplingHookPlugin
name: GrapplingHook
version: 3.6
author: juddcraft12
description: Grappling hook
softdepend: [Slimefun]
commands:
  grapplinghook:
    description: Grappling Hook Commands
    aliases: [gh]
    usage: |
      /gh give <player> -Grappling hook with unlimited uses
      /gh give <player> <uses> - Grappling hook with limited uses
      /gh debug - Toggling debug logging in console
      /gh reload - Reload configuration
permissions:
  grapplinghook.give:
    default: op
  grapplinghook.debug:
    default: op
  grapplinghook.reload:
    default: op
  grapplinghook.use:
    default: true
  grapplinghook.craft:
    default: true
    api-version: 1.14
